### ISSUE TITLE
Can't compile due to relative module missing

### ISSUE THREAD

**Issue by atymic** [johannes-z/office-fabric#12]
Fresh Vue cli project. Deps below. It also forced me to install react as it seems it's a dependency of this lib?

``` 
 "dependencies": {
    "@uifabric-vue/office-ui-fabric-vue": "^8.1.0",
    "@uifabric/merge-styles": "^7.19.1",
    "@uifabric/styling": "^7.17.1",
    "core-js": "^3.6.5",
    "office-toolbox": "^0.1.1",
    "react": "^17.0.1",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
```

```This relative module was not found:

* ../utilities in ./node_modules/@uifabric-vue/office-ui-fabric-vue/lib/plugin/office-fabric.js```

**Comment by atymic** [comment]
Also, webpack config is:

```
configureWebpack: {
    resolve: {
      alias: {
        '@uifabric/utilities': '@uifabric-vue/utilities',
      },
    },
  }
```

**Comment by atymic** [comment]
Node version: `v14.15.5`

**Comment by atymic** [comment]
File tree 
![image](https://user-images.githubusercontent.com/50683531/107468222-b4203c80-6bbb-11eb-839b-5af907d980e8.png)

**Comment by atymic** [comment]
I think it might be trying to import the Utilities.ts file in the directory above maybe?

**Comment by johannes-z** [comment]
Yes, `react` will be installed automatically caused it's a transitive dependency of `@uifabric/utilities` which is again used in e.g. `@uifabric/styling`. It's unused however, because of the defined alias.

I also didn't see `@uifabric-vue/utilities` in your dependencies - can you add it and check if it then works? 

To be honest I'm only using the Fabric plugin in the official website (where it also works) - for other projects I'm directly importing the components I need.

**Comment by atymic** [comment]
I actually did install that while debugging, unfortunately didn't fix it. 

Deps:
```
"dependencies": {
    "@uifabric-vue/office-ui-fabric-vue": "^8.1.0",
    "@uifabric-vue/utilities": "^7.32.4-1",
    "@uifabric/merge-styles": "^7.19.1",
    "@uifabric/styling": "^7.17.1",
    "core-js": "^3.6.5",
    "office-toolbox": "^0.1.1",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  }
```

Errors:
```
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme@1.7.2" has unmet peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme@1.7.2" has unmet peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme@1.7.2" has unmet peer dependency "react@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme@1.7.2" has unmet peer dependency "react-dom@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme > @uifabric/utilities@7.33.3" has unmet peer dependency "@types/react@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme > @uifabric/utilities@7.33.3" has unmet peer dependency "@types/react-dom@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme > @uifabric/utilities@7.33.3" has unmet peer dependency "react@>=16.8.0 <17.0.0".
warning "@uifabric-vue/office-ui-fabric-vue > @fluentui/theme > @uifabric/utilities@7.33.3" has unmet peer dependency "react-dom@>=16.8.0 <17.0.0".

```

**Comment by atymic** [comment]
In fact, just adding the components directly after importing them also causes the same error 🤔
![image](https://user-images.githubusercontent.com/50683531/107576219-f3df3680-6c44-11eb-8f01-03a3a9703d07.png)

I think this has to be something to do with node version mismatch or something related to case insensitive capitalisation on mac.

**Comment by atymic** [comment]
I was able to get solve errors one by one by changing the imports from
`import { ResponsiveMode } from '../../utilities';` to `import ResponsiveMode from '../../utilities/responsiveMode';`

Not that that helps as there's tons, clearly the loader isn't working properly.

**Comment by johannes-z** [comment]
Strange, I just created a new project using vue cli, added `@uifabric-vue/office-ui-fabric-vue` and it works just fine:

node: v14.15.0
npm: 6.14.9

package.json:

```json
  "dependencies": {
    "@uifabric-vue/office-ui-fabric-vue": "^8.1.0",
    "@uifabric-vue/utilities": "^7.32.4-1",
    "@uifabric/merge-styles": "^7.19.1",
    "@uifabric/styling": "^7.17.1",
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
```

vue.config.js

```js
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        '@uifabric/utilities': '@uifabric-vue/utilities',
      },
    },
  }
}
```

App.vue

```vue
<template>
  <div id="app">
    <Toggle />
  </div>
</template>

<script>
import { Toggle } from '@uifabric-vue/office-ui-fabric-vue'

export default {
  name: 'App',
  components: {
    Toggle
  }
}
</script>
```

What OS are you on?

**Comment by atymic** [comment]
let me try that, on OSX Big Sur

**Comment by atymic** [comment]
Just copied your steps and config exactly, got exact same error 🙃:

```
 ERROR  Failed to compile with 1 error                                                                                                                                                                                                           10:01:48 pm

This relative module was not found:

* ../utilities in ./node_modules/@uifabric-vue/office-ui-fabric-vue/lib/plugin/office-fabric.js
```

**Comment by atymic** [comment]
Default used yarn, which is 1.22.10
Also tried npm, 6.14.11

**Comment by atymic** [comment]
Default used yarn, which is 1.22.10
Also tried npm, 6.14.11

**Comment by atymic** [comment]
A little update here. Revisited this and I think my guess was right (case sensitivity issues)

I built a little dockerfile, and it worked ok and built correctly. Im guessing you're on linux locally?
https://gist.github.com/atymic/56f2908e8845d47c8056b3b3e510a562

I still don't know why the case sensitivity breaks it though :(

**Comment by johannes-z** [comment]
@atymic Thanks for looking into the issue and the PR! I'm wondering if I should keep the `Utilities.ts` as this seems to be a relict of the official fabric to import from `@uifabric/utilities` .
Let me know if it works for you now!

**Comment by atymic** [comment]
Sweet, it works :D 

Thanks again for your help 👍
