### ISSUE TITLE
Issues with the Dropdown component

### ISSUE THREAD

**Issue by WillemJann** [johannes-z/office-fabric#16]
First of all, thank you for making `Office UI Fabric React` available in Vue. We make grateful use of it in one of our projects. I know this is work-in-progress, but I hope it's helpful when bugs are reported.

I found some issues with the Dropdown component. Let's assume we have a single-select dropdown.

* Select 'Option A', and then again select 'Option A'. The selected value is cleared and the call-out remains open, this not expected. Expected behavior: https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
* The selected value it not highlighted in the call-out.
* There is no hover effect (grey background) in the call-out.
* Clicking on the dropdown should toggle the call-out, not always open the call-out.
* This component has no `v-modal`. I suggest that the selected value(s) should be exposed, just like CheckBox and ChoiceGroup.

**Comment by johannes-z** [comment]
@WillemJann Sorry for the delay. Let me know if this fixes your issues.
